
package ProjectoFinalSalud.Vistas;

import ProjectoFinalSalud.AccesoDeDatos.AfiliadoData;
import ProjectoFinalSalud.Entidades.Afiliado;
import java.awt.Cursor;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.plaf.basic.BasicInternalFrameUI;

public class AfiliadosAgregarOAnular extends javax.swing.JInternalFrame {

    AfiliadoData ad = new AfiliadoData();
    
    public AfiliadosAgregarOAnular() {
        
        initComponents();
        
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        BasicInternalFrameUI bui = (BasicInternalFrameUI) this.getUI();
        bui.setNorthPane(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelGradAfiAgreOAnul = new keeptoo.KGradientPanel();
        etiquetaAfiAgreYAnul = new javax.swing.JLabel();
        etiquetaAfiNumDoc = new javax.swing.JLabel();
        etiquetaAfiNomYApe = new javax.swing.JLabel();
        etiquetaAfiNumTel = new javax.swing.JLabel();
        etiquetaAfiDom = new javax.swing.JLabel();
        etiquetaAfiEstado = new javax.swing.JLabel();
        etiquetaAfiEstAcONoac = new javax.swing.JLabel();
        textoAfiAgreYAnulDNI = new javax.swing.JTextField();
        textoAfiAgreYAnulNomYApe = new javax.swing.JTextField();
        textoAfiAgreYAnulNumTel = new javax.swing.JTextField();
        textoAfiAgreYAnulDom = new javax.swing.JTextField();
        botonAfiAgreYAnulBuscar = new javax.swing.JButton();
        botonAfiAgreYAnulRein = new javax.swing.JButton();
        botonAfiAgreYAnulGuardar = new javax.swing.JButton();
        botonAfiAgreYAnulAnular = new javax.swing.JButton();
        botonAtrasAfiAgreYAnul = new javax.swing.JButton();
        separadorAfiAgreYAnul = new javax.swing.JSeparator();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(975, 575));

        panelGradAfiAgreOAnul.setBackground(new java.awt.Color(255, 255, 255));
        panelGradAfiAgreOAnul.setkEndColor(new java.awt.Color(0, 153, 255));
        panelGradAfiAgreOAnul.setkStartColor(new java.awt.Color(0, 153, 0));
        panelGradAfiAgreOAnul.setPreferredSize(new java.awt.Dimension(975, 575));

        etiquetaAfiAgreYAnul.setBackground(new java.awt.Color(255, 255, 255));
        etiquetaAfiAgreYAnul.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        etiquetaAfiAgreYAnul.setForeground(new java.awt.Color(255, 255, 255));
        etiquetaAfiAgreYAnul.setText("Agregar Y Anular Afiliados");

        etiquetaAfiNumDoc.setBackground(new java.awt.Color(255, 255, 255));
        etiquetaAfiNumDoc.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        etiquetaAfiNumDoc.setForeground(new java.awt.Color(255, 255, 255));
        etiquetaAfiNumDoc.setText("Número de Documento:");

        etiquetaAfiNomYApe.setBackground(new java.awt.Color(255, 255, 255));
        etiquetaAfiNomYApe.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        etiquetaAfiNomYApe.setForeground(new java.awt.Color(255, 255, 255));
        etiquetaAfiNomYApe.setText("Nombre y Apellido:");

        etiquetaAfiNumTel.setBackground(new java.awt.Color(255, 255, 255));
        etiquetaAfiNumTel.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        etiquetaAfiNumTel.setForeground(new java.awt.Color(255, 255, 255));
        etiquetaAfiNumTel.setText("Número de Teléfono:");

        etiquetaAfiDom.setBackground(new java.awt.Color(255, 255, 255));
        etiquetaAfiDom.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        etiquetaAfiDom.setForeground(new java.awt.Color(255, 255, 255));
        etiquetaAfiDom.setText("Domicilio:");

        etiquetaAfiEstado.setBackground(new java.awt.Color(255, 255, 255));
        etiquetaAfiEstado.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        etiquetaAfiEstado.setForeground(new java.awt.Color(255, 255, 255));
        etiquetaAfiEstado.setText("Estado:");

        etiquetaAfiEstAcONoac.setBackground(new java.awt.Color(255, 255, 255));
        etiquetaAfiEstAcONoac.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        etiquetaAfiEstAcONoac.setForeground(new java.awt.Color(255, 255, 255));

        textoAfiAgreYAnulDNI.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N

        textoAfiAgreYAnulNomYApe.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N

        textoAfiAgreYAnulNumTel.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N

        textoAfiAgreYAnulDom.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N

        botonAfiAgreYAnulBuscar.setBackground(new java.awt.Color(255, 255, 255));
        botonAfiAgreYAnulBuscar.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        botonAfiAgreYAnulBuscar.setForeground(new java.awt.Color(255, 255, 255));
        botonAfiAgreYAnulBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagenesDelProyecto/Boton.png"))); // NOI18N
        botonAfiAgreYAnulBuscar.setText("Buscar");
        botonAfiAgreYAnulBuscar.setBorderPainted(false);
        botonAfiAgreYAnulBuscar.setContentAreaFilled(false);
        botonAfiAgreYAnulBuscar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        botonAfiAgreYAnulBuscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botonAfiAgreYAnulBuscarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botonAfiAgreYAnulBuscarMouseExited(evt);
            }
        });
        botonAfiAgreYAnulBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAfiAgreYAnulBuscarActionPerformed(evt);
            }
        });

        botonAfiAgreYAnulRein.setBackground(new java.awt.Color(255, 255, 255));
        botonAfiAgreYAnulRein.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        botonAfiAgreYAnulRein.setForeground(new java.awt.Color(255, 255, 255));
        botonAfiAgreYAnulRein.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagenesDelProyecto/Boton.png"))); // NOI18N
        botonAfiAgreYAnulRein.setText("Reinstituir");
        botonAfiAgreYAnulRein.setBorderPainted(false);
        botonAfiAgreYAnulRein.setContentAreaFilled(false);
        botonAfiAgreYAnulRein.setEnabled(false);
        botonAfiAgreYAnulRein.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        botonAfiAgreYAnulRein.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botonAfiAgreYAnulReinMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botonAfiAgreYAnulReinMouseExited(evt);
            }
        });
        botonAfiAgreYAnulRein.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAfiAgreYAnulReinActionPerformed(evt);
            }
        });

        botonAfiAgreYAnulGuardar.setBackground(new java.awt.Color(255, 255, 255));
        botonAfiAgreYAnulGuardar.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        botonAfiAgreYAnulGuardar.setForeground(new java.awt.Color(255, 255, 255));
        botonAfiAgreYAnulGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagenesDelProyecto/Boton.png"))); // NOI18N
        botonAfiAgreYAnulGuardar.setText("Guardar");
        botonAfiAgreYAnulGuardar.setBorderPainted(false);
        botonAfiAgreYAnulGuardar.setContentAreaFilled(false);
        botonAfiAgreYAnulGuardar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        botonAfiAgreYAnulGuardar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botonAfiAgreYAnulGuardarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botonAfiAgreYAnulGuardarMouseExited(evt);
            }
        });
        botonAfiAgreYAnulGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAfiAgreYAnulGuardarActionPerformed(evt);
            }
        });

        botonAfiAgreYAnulAnular.setBackground(new java.awt.Color(255, 255, 255));
        botonAfiAgreYAnulAnular.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        botonAfiAgreYAnulAnular.setForeground(new java.awt.Color(255, 255, 255));
        botonAfiAgreYAnulAnular.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagenesDelProyecto/Boton.png"))); // NOI18N
        botonAfiAgreYAnulAnular.setText("Anular");
        botonAfiAgreYAnulAnular.setBorderPainted(false);
        botonAfiAgreYAnulAnular.setContentAreaFilled(false);
        botonAfiAgreYAnulAnular.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        botonAfiAgreYAnulAnular.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botonAfiAgreYAnulAnularMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botonAfiAgreYAnulAnularMouseExited(evt);
            }
        });
        botonAfiAgreYAnulAnular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAfiAgreYAnulAnularActionPerformed(evt);
            }
        });

        botonAtrasAfiAgreYAnul.setBackground(new java.awt.Color(255, 255, 255));
        botonAtrasAfiAgreYAnul.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        botonAtrasAfiAgreYAnul.setForeground(new java.awt.Color(255, 255, 255));
        botonAtrasAfiAgreYAnul.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagenesDelProyecto/BotonRetroceso.png"))); // NOI18N
        botonAtrasAfiAgreYAnul.setText("Atrás");
        botonAtrasAfiAgreYAnul.setBorderPainted(false);
        botonAtrasAfiAgreYAnul.setContentAreaFilled(false);
        botonAtrasAfiAgreYAnul.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        botonAtrasAfiAgreYAnul.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botonAtrasAfiAgreYAnulMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botonAtrasAfiAgreYAnulMouseExited(evt);
            }
        });
        botonAtrasAfiAgreYAnul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAtrasAfiAgreYAnulActionPerformed(evt);
            }
        });

        separadorAfiAgreYAnul.setForeground(new java.awt.Color(255, 255, 255));
        separadorAfiAgreYAnul.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));

        javax.swing.GroupLayout panelGradAfiAgreOAnulLayout = new javax.swing.GroupLayout(panelGradAfiAgreOAnul);
        panelGradAfiAgreOAnul.setLayout(panelGradAfiAgreOAnulLayout);
        panelGradAfiAgreOAnulLayout.setHorizontalGroup(
            panelGradAfiAgreOAnulLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelGradAfiAgreOAnulLayout.createSequentialGroup()
                .addGroup(panelGradAfiAgreOAnulLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelGradAfiAgreOAnulLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(etiquetaAfiAgreYAnul)
                        .addGap(215, 215, 215)
                        .addComponent(botonAtrasAfiAgreYAnul))
                    .addGroup(panelGradAfiAgreOAnulLayout.createSequentialGroup()
                        .addGroup(panelGradAfiAgreOAnulLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(botonAfiAgreYAnulGuardar)
                            .addGroup(panelGradAfiAgreOAnulLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(panelGradAfiAgreOAnulLayout.createSequentialGroup()
                                    .addGap(171, 171, 171)
                                    .addComponent(etiquetaAfiNumDoc)
                                    .addGap(18, 18, 18)
                                    .addComponent(textoAfiAgreYAnulDNI, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelGradAfiAgreOAnulLayout.createSequentialGroup()
                                    .addGap(141, 141, 141)
                                    .addGroup(panelGradAfiAgreOAnulLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(botonAfiAgreYAnulBuscar, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(separadorAfiAgreYAnul, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 611, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(panelGradAfiAgreOAnulLayout.createSequentialGroup()
                                    .addGap(190, 190, 190)
                                    .addGroup(panelGradAfiAgreOAnulLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(panelGradAfiAgreOAnulLayout.createSequentialGroup()
                                            .addComponent(etiquetaAfiNumTel)
                                            .addGap(18, 18, 18)
                                            .addComponent(textoAfiAgreYAnulNumTel, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(panelGradAfiAgreOAnulLayout.createSequentialGroup()
                                            .addComponent(etiquetaAfiNomYApe)
                                            .addGap(18, 18, 18)
                                            .addComponent(textoAfiAgreYAnulNomYApe, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(panelGradAfiAgreOAnulLayout.createSequentialGroup()
                                            .addGroup(panelGradAfiAgreOAnulLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(etiquetaAfiEstado)
                                                .addComponent(etiquetaAfiDom))
                                            .addGap(18, 18, 18)
                                            .addGroup(panelGradAfiAgreOAnulLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(textoAfiAgreYAnulDom, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(etiquetaAfiEstAcONoac, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(botonAfiAgreYAnulRein)))
                            .addComponent(botonAfiAgreYAnulAnular))
                        .addGap(0, 197, Short.MAX_VALUE)))
                .addContainerGap())
        );
        panelGradAfiAgreOAnulLayout.setVerticalGroup(
            panelGradAfiAgreOAnulLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelGradAfiAgreOAnulLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelGradAfiAgreOAnulLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(botonAtrasAfiAgreYAnul)
                    .addComponent(etiquetaAfiAgreYAnul))
                .addGap(45, 45, 45)
                .addGroup(panelGradAfiAgreOAnulLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonAfiAgreYAnulBuscar)
                    .addComponent(textoAfiAgreYAnulDNI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(etiquetaAfiNumDoc))
                .addGap(27, 27, 27)
                .addComponent(separadorAfiAgreYAnul, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addGroup(panelGradAfiAgreOAnulLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textoAfiAgreYAnulNomYApe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(etiquetaAfiNomYApe))
                .addGap(18, 18, 18)
                .addGroup(panelGradAfiAgreOAnulLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textoAfiAgreYAnulNumTel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(etiquetaAfiNumTel))
                .addGap(18, 18, 18)
                .addGroup(panelGradAfiAgreOAnulLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelGradAfiAgreOAnulLayout.createSequentialGroup()
                        .addGroup(panelGradAfiAgreOAnulLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(textoAfiAgreYAnulDom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(etiquetaAfiDom))
                        .addGap(18, 18, 18)
                        .addGroup(panelGradAfiAgreOAnulLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(etiquetaAfiEstado)
                            .addComponent(etiquetaAfiEstAcONoac, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(botonAfiAgreYAnulRein))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botonAfiAgreYAnulGuardar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botonAfiAgreYAnulAnular)
                .addContainerGap(38, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelGradAfiAgreOAnul, javax.swing.GroupLayout.DEFAULT_SIZE, 959, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelGradAfiAgreOAnul, javax.swing.GroupLayout.DEFAULT_SIZE, 545, Short.MAX_VALUE)
        );

        setBounds(0, 0, 975, 575);
    }// </editor-fold>//GEN-END:initComponents

    private void botonAfiAgreYAnulAnularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAfiAgreYAnulAnularActionPerformed
        try{
            int dni=Integer.parseInt(textoAfiAgreYAnulDNI.getText());
            ad.borrarAfiliado(dni);
        }catch(NumberFormatException ne){
            JOptionPane.showMessageDialog(null, "Ingrese el número de documento de un Afiliado para anularlo");
        }catch(NullPointerException np){
            JOptionPane.showMessageDialog(null, "Tiene que ingresar el DNI de un Afiliado para anularlo");
        }
        limpiar();
    }//GEN-LAST:event_botonAfiAgreYAnulAnularActionPerformed

    private void botonAfiAgreYAnulGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAfiAgreYAnulGuardarActionPerformed
       try{
           if(textoAfiAgreYAnulDNI.getText().isEmpty() || textoAfiAgreYAnulNumTel.getText().isEmpty()){
               JOptionPane.showMessageDialog(null, "Tiene que llenar la planilla para ingresar un Afiliado");
           }else if(buscarDni(Integer.parseInt(textoAfiAgreYAnulDNI.getText()))){
               JOptionPane.showMessageDialog(null, "El Documento ingresado ya le pertenece a un Afiliado registrado");
           }else{
               int dni=Integer.parseInt(textoAfiAgreYAnulDNI.getText());
               int tel=Integer.parseInt(textoAfiAgreYAnulNumTel.getText());
               Afiliado afiliado=new Afiliado();
               afiliado.setDni(dni);
               afiliado.setNombre(textoAfiAgreYAnulNomYApe.getText());
               afiliado.setTelefono(tel);
               afiliado.setDomicilio(textoAfiAgreYAnulDom.getText());
               afiliado.setActivo(true);
               ad.guardarAfiliado(afiliado);
           }
       }catch(NumberFormatException ne){
           JOptionPane.showMessageDialog(null, "Error al ingresar, caracteres equivocados");
       }catch(NullPointerException np){
           JOptionPane.showMessageDialog(null, "Tiene que llenar la planilla para ingresar un Afiliado");
       }
        limpiar();
    }//GEN-LAST:event_botonAfiAgreYAnulGuardarActionPerformed

    private void botonAfiAgreYAnulBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAfiAgreYAnulBuscarActionPerformed
        try{
        int dni=Integer.parseInt(textoAfiAgreYAnulDNI.getText());
        botonAfiAgreYAnulGuardar.setEnabled(false);
        Afiliado af=ad.buscarAfiliados(dni);
        if(af.getTelefono()==0){
            limpiar();
        }else{
        textoAfiAgreYAnulNomYApe.setText(af.getNombre());
        textoAfiAgreYAnulDom.setText(af.getDomicilio());
        textoAfiAgreYAnulNumTel.setText(af.getTelefono()+"");
        if(af.isActivo()){
            etiquetaAfiEstAcONoac.setText("Activo");
            botonAfiAgreYAnulRein.setEnabled(false);
            
        }else{
            etiquetaAfiEstAcONoac.setText("Inactivo");
            botonAfiAgreYAnulRein.setEnabled(true);
        }
        }
        }catch(NumberFormatException ne){
           JOptionPane.showMessageDialog(null, "Ingrese un número de documento válido para buscar a un Afiliado");
           limpiar();
       }
    }//GEN-LAST:event_botonAfiAgreYAnulBuscarActionPerformed

    private void botonAfiAgreYAnulReinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAfiAgreYAnulReinActionPerformed
        int dni = Integer.parseInt(textoAfiAgreYAnulDNI.getText());
        ad.reinstituirAfliliado(dni);
        limpiar();
    }//GEN-LAST:event_botonAfiAgreYAnulReinActionPerformed

    private void botonAtrasAfiAgreYAnulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAtrasAfiAgreYAnulActionPerformed
        dispose();
    }//GEN-LAST:event_botonAtrasAfiAgreYAnulActionPerformed

    private void botonAtrasAfiAgreYAnulMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonAtrasAfiAgreYAnulMouseEntered
        setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_botonAtrasAfiAgreYAnulMouseEntered

    private void botonAtrasAfiAgreYAnulMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonAtrasAfiAgreYAnulMouseExited
        setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_botonAtrasAfiAgreYAnulMouseExited

    private void botonAfiAgreYAnulBuscarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonAfiAgreYAnulBuscarMouseEntered
        setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_botonAfiAgreYAnulBuscarMouseEntered

    private void botonAfiAgreYAnulBuscarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonAfiAgreYAnulBuscarMouseExited
        setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_botonAfiAgreYAnulBuscarMouseExited

    private void botonAfiAgreYAnulReinMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonAfiAgreYAnulReinMouseEntered
        setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_botonAfiAgreYAnulReinMouseEntered

    private void botonAfiAgreYAnulReinMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonAfiAgreYAnulReinMouseExited
        setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_botonAfiAgreYAnulReinMouseExited

    private void botonAfiAgreYAnulGuardarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonAfiAgreYAnulGuardarMouseEntered
        setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_botonAfiAgreYAnulGuardarMouseEntered

    private void botonAfiAgreYAnulGuardarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonAfiAgreYAnulGuardarMouseExited
        setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_botonAfiAgreYAnulGuardarMouseExited

    private void botonAfiAgreYAnulAnularMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonAfiAgreYAnulAnularMouseEntered
        setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_botonAfiAgreYAnulAnularMouseEntered

    private void botonAfiAgreYAnulAnularMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonAfiAgreYAnulAnularMouseExited
        setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_botonAfiAgreYAnulAnularMouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonAfiAgreYAnulAnular;
    private javax.swing.JButton botonAfiAgreYAnulBuscar;
    private javax.swing.JButton botonAfiAgreYAnulGuardar;
    private javax.swing.JButton botonAfiAgreYAnulRein;
    private javax.swing.JButton botonAtrasAfiAgreYAnul;
    private javax.swing.JLabel etiquetaAfiAgreYAnul;
    private javax.swing.JLabel etiquetaAfiDom;
    private javax.swing.JLabel etiquetaAfiEstAcONoac;
    private javax.swing.JLabel etiquetaAfiEstado;
    private javax.swing.JLabel etiquetaAfiNomYApe;
    private javax.swing.JLabel etiquetaAfiNumDoc;
    private javax.swing.JLabel etiquetaAfiNumTel;
    private keeptoo.KGradientPanel panelGradAfiAgreOAnul;
    private javax.swing.JSeparator separadorAfiAgreYAnul;
    private javax.swing.JTextField textoAfiAgreYAnulDNI;
    private javax.swing.JTextField textoAfiAgreYAnulDom;
    private javax.swing.JTextField textoAfiAgreYAnulNomYApe;
    private javax.swing.JTextField textoAfiAgreYAnulNumTel;
    // End of variables declaration//GEN-END:variables

    private void limpiar(){
        textoAfiAgreYAnulDNI.setText("");
        textoAfiAgreYAnulDom.setText("");
        textoAfiAgreYAnulNomYApe.setText("");
        textoAfiAgreYAnulNumTel.setText("");
        etiquetaAfiEstAcONoac.setText("");
        botonAfiAgreYAnulRein.setEnabled(false);
        botonAfiAgreYAnulGuardar.setEnabled(true);
    }
    
    private boolean buscarDni(int dni) {
        ArrayList<Afiliado> afiliado = ad.listarAfiliados();
        boolean a = false;
        for (Afiliado afi : afiliado) {
            if (afi.getDni() == dni) {
                a = true;
                return a;
            }
        }
        return a;
    }
}
