
package ProjectoFinalSalud.Vistas;

import ProjectoFinalSalud.AccesoDeDatos.AfiliadoData;
import ProjectoFinalSalud.Entidades.Afiliado;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import javax.swing.table.DefaultTableModel;

public class AfiliadosLista extends javax.swing.JInternalFrame {
    
    DefaultTableModel modelo = new DefaultTableModel(){
        @Override
        public boolean isCellEditable(int row, int colum) {
            return false;
        }
    };
    
    AfiliadoData ad=new AfiliadoData();
    
    public AfiliadosLista() {
        
        initComponents();
        armarCabesera();
        cargarTabla();
        
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        BasicInternalFrameUI bui = (BasicInternalFrameUI) this.getUI();
        bui.setNorthPane(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelGradAfiLista = new keeptoo.KGradientPanel();
        etiquetaAfiListaAfi = new javax.swing.JLabel();
        etiquetaAfiTotal = new javax.swing.JLabel();
        etiquetaAfiTotalAfi = new javax.swing.JLabel();
        botonAtrasAfiLista = new javax.swing.JButton();
        panelScrollTablaListaAfi = new javax.swing.JScrollPane();
        tablaListaAfi = new javax.swing.JTable();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(975, 575));

        panelGradAfiLista.setBackground(new java.awt.Color(255, 255, 255));
        panelGradAfiLista.setkEndColor(new java.awt.Color(0, 153, 255));
        panelGradAfiLista.setkStartColor(new java.awt.Color(0, 153, 0));
        panelGradAfiLista.setPreferredSize(new java.awt.Dimension(975, 575));

        etiquetaAfiListaAfi.setBackground(new java.awt.Color(255, 255, 255));
        etiquetaAfiListaAfi.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        etiquetaAfiListaAfi.setForeground(new java.awt.Color(255, 255, 255));
        etiquetaAfiListaAfi.setText("Lista De Afiliados");

        etiquetaAfiTotal.setBackground(new java.awt.Color(255, 255, 255));
        etiquetaAfiTotal.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        etiquetaAfiTotal.setForeground(new java.awt.Color(255, 255, 255));
        etiquetaAfiTotal.setText("Total de Afiliados en la Lista:");

        etiquetaAfiTotalAfi.setBackground(new java.awt.Color(255, 255, 255));
        etiquetaAfiTotalAfi.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
        etiquetaAfiTotalAfi.setForeground(new java.awt.Color(255, 255, 255));

        botonAtrasAfiLista.setBackground(new java.awt.Color(255, 255, 255));
        botonAtrasAfiLista.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        botonAtrasAfiLista.setForeground(new java.awt.Color(255, 255, 255));
        botonAtrasAfiLista.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagenesDelProyecto/BotonRetroceso.png"))); // NOI18N
        botonAtrasAfiLista.setText("Atrás");
        botonAtrasAfiLista.setBorderPainted(false);
        botonAtrasAfiLista.setContentAreaFilled(false);
        botonAtrasAfiLista.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        botonAtrasAfiLista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAtrasAfiListaActionPerformed(evt);
            }
        });

        tablaListaAfi.setBackground(panelGradAfiLista.getkStartColor());
        tablaListaAfi.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        tablaListaAfi.setForeground(new java.awt.Color(255, 255, 255));
        tablaListaAfi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablaListaAfi.getTableHeader().setReorderingAllowed(false);
        panelScrollTablaListaAfi.setViewportView(tablaListaAfi);
        if (tablaListaAfi.getColumnModel().getColumnCount() > 0) {
            tablaListaAfi.getColumnModel().getColumn(0).setResizable(false);
            tablaListaAfi.getColumnModel().getColumn(1).setResizable(false);
            tablaListaAfi.getColumnModel().getColumn(2).setResizable(false);
            tablaListaAfi.getColumnModel().getColumn(3).setResizable(false);
        }

        javax.swing.GroupLayout panelGradAfiListaLayout = new javax.swing.GroupLayout(panelGradAfiLista);
        panelGradAfiLista.setLayout(panelGradAfiListaLayout);
        panelGradAfiListaLayout.setHorizontalGroup(
            panelGradAfiListaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelGradAfiListaLayout.createSequentialGroup()
                .addGap(106, 106, 106)
                .addGroup(panelGradAfiListaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelGradAfiListaLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(etiquetaAfiListaAfi)
                        .addGap(248, 248, 248)
                        .addComponent(botonAtrasAfiLista))
                    .addGroup(panelGradAfiListaLayout.createSequentialGroup()
                        .addGroup(panelGradAfiListaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelGradAfiListaLayout.createSequentialGroup()
                                .addComponent(etiquetaAfiTotal)
                                .addGap(18, 18, 18)
                                .addComponent(etiquetaAfiTotalAfi, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(panelScrollTablaListaAfi, javax.swing.GroupLayout.PREFERRED_SIZE, 718, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 125, Short.MAX_VALUE)))
                .addContainerGap())
        );
        panelGradAfiListaLayout.setVerticalGroup(
            panelGradAfiListaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelGradAfiListaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelGradAfiListaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(botonAtrasAfiLista)
                    .addComponent(etiquetaAfiListaAfi))
                .addGap(57, 57, 57)
                .addComponent(panelScrollTablaListaAfi, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(panelGradAfiListaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelGradAfiListaLayout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(etiquetaAfiTotal))
                    .addGroup(panelGradAfiListaLayout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(etiquetaAfiTotalAfi, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(169, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelGradAfiLista, javax.swing.GroupLayout.DEFAULT_SIZE, 959, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelGradAfiLista, javax.swing.GroupLayout.DEFAULT_SIZE, 545, Short.MAX_VALUE)
        );

        setBounds(0, 0, 975, 575);
    }// </editor-fold>//GEN-END:initComponents

    private void botonAtrasAfiListaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAtrasAfiListaActionPerformed
        dispose();
    }//GEN-LAST:event_botonAtrasAfiListaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonAtrasAfiLista;
    private javax.swing.JLabel etiquetaAfiListaAfi;
    private javax.swing.JLabel etiquetaAfiTotal;
    private javax.swing.JLabel etiquetaAfiTotalAfi;
    private keeptoo.KGradientPanel panelGradAfiLista;
    private javax.swing.JScrollPane panelScrollTablaListaAfi;
    private javax.swing.JTable tablaListaAfi;
    // End of variables declaration//GEN-END:variables
    
    private void armarCabesera(){
        modelo.addColumn("ID");
        modelo.addColumn("Nombre y Apellido");
        modelo.addColumn("Número de Documento");
        modelo.addColumn("Número Telefónico");
        modelo.addColumn("Domicilio");
        tablaListaAfi.setModel(modelo);
    }
  
    private void cargarTabla(){
        for(Afiliado afi:ad.listarAfiliados()){
            modelo.addRow(new Object[]{afi.getIdAfiliado(),afi.getNombre(),afi.getDni(),afi.getTelefono(),afi.getDomicilio()});
        }
        cantAfiliadosActivos();
    }
    
    private void cantAfiliadosActivos(){
        int num=tablaListaAfi.getRowCount();
        etiquetaAfiTotalAfi.setText(num+"");
    }
}
