package ProjectoFinalSalud.Vistas;

import java.awt.Cursor;
import javax.swing.JInternalFrame;
import javax.swing.plaf.basic.BasicInternalFrameUI;

public class Afiliados extends javax.swing.JInternalFrame {

    public Afiliados() {

        initComponents();

        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        BasicInternalFrameUI bui = (BasicInternalFrameUI) this.getUI();
        bui.setNorthPane(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelGradAfi = new keeptoo.KGradientPanel();
        botonAtrasAfi = new javax.swing.JButton();
        menuAfi = new javax.swing.JMenuBar();
        menuAfiListaAfi = new javax.swing.JMenu();
        menuItemAfiLista = new javax.swing.JMenuItem();
        menuAfiHabiODeshAfi = new javax.swing.JMenu();
        menuItemAfiHabYDes = new javax.swing.JMenuItem();
        menuAfiMod = new javax.swing.JMenu();
        menuItemAfiMod = new javax.swing.JMenuItem();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(975, 575));

        panelGradAfi.setBackground(new java.awt.Color(255, 255, 255));
        panelGradAfi.setkEndColor(new java.awt.Color(0, 153, 255));
        panelGradAfi.setkStartColor(new java.awt.Color(0, 153, 0));
        panelGradAfi.setPreferredSize(new java.awt.Dimension(975, 575));

        botonAtrasAfi.setBackground(new java.awt.Color(255, 255, 255));
        botonAtrasAfi.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        botonAtrasAfi.setForeground(new java.awt.Color(255, 255, 255));
        botonAtrasAfi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagenesDelProyecto/BotonRetroceso.png"))); // NOI18N
        botonAtrasAfi.setText("Atrás");
        botonAtrasAfi.setBorderPainted(false);
        botonAtrasAfi.setContentAreaFilled(false);
        botonAtrasAfi.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        botonAtrasAfi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botonAtrasAfiMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botonAtrasAfiMouseExited(evt);
            }
        });
        botonAtrasAfi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAtrasAfiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelGradAfiLayout = new javax.swing.GroupLayout(panelGradAfi);
        panelGradAfi.setLayout(panelGradAfiLayout);
        panelGradAfiLayout.setHorizontalGroup(
            panelGradAfiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelGradAfiLayout.createSequentialGroup()
                .addContainerGap(796, Short.MAX_VALUE)
                .addComponent(botonAtrasAfi)
                .addContainerGap())
        );
        panelGradAfiLayout.setVerticalGroup(
            panelGradAfiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelGradAfiLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(botonAtrasAfi)
                .addContainerGap(460, Short.MAX_VALUE))
        );

        menuAfiListaAfi.setBackground(new java.awt.Color(255, 255, 255));
        menuAfiListaAfi.setText("Lista De Afiliados");
        menuAfiListaAfi.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        menuAfiListaAfi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                menuAfiListaAfiMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                menuAfiListaAfiMouseExited(evt);
            }
        });

        menuItemAfiLista.setBackground(new java.awt.Color(255, 255, 255));
        menuItemAfiLista.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        menuItemAfiLista.setText("Lista De Afiliados");
        menuItemAfiLista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemAfiListaActionPerformed(evt);
            }
        });
        menuAfiListaAfi.add(menuItemAfiLista);

        menuAfi.add(menuAfiListaAfi);

        menuAfiHabiODeshAfi.setBackground(new java.awt.Color(255, 255, 255));
        menuAfiHabiODeshAfi.setText("Habilitar O Deshabilitar Afiliados");
        menuAfiHabiODeshAfi.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        menuAfiHabiODeshAfi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                menuAfiHabiODeshAfiMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                menuAfiHabiODeshAfiMouseExited(evt);
            }
        });

        menuItemAfiHabYDes.setBackground(new java.awt.Color(255, 255, 255));
        menuItemAfiHabYDes.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        menuItemAfiHabYDes.setText("Habilitar O Deshabilitar");
        menuItemAfiHabYDes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemAfiHabYDesActionPerformed(evt);
            }
        });
        menuAfiHabiODeshAfi.add(menuItemAfiHabYDes);

        menuAfi.add(menuAfiHabiODeshAfi);

        menuAfiMod.setBackground(new java.awt.Color(255, 255, 255));
        menuAfiMod.setText("Modificar Datos De Un Afiliado");
        menuAfiMod.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        menuAfiMod.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                menuAfiModMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                menuAfiModMouseExited(evt);
            }
        });

        menuItemAfiMod.setBackground(new java.awt.Color(255, 255, 255));
        menuItemAfiMod.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        menuItemAfiMod.setText("Modificar");
        menuItemAfiMod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemAfiModActionPerformed(evt);
            }
        });
        menuAfiMod.add(menuItemAfiMod);

        menuAfi.add(menuAfiMod);

        setJMenuBar(menuAfi);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelGradAfi, javax.swing.GroupLayout.DEFAULT_SIZE, 959, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelGradAfi, javax.swing.GroupLayout.DEFAULT_SIZE, 524, Short.MAX_VALUE)
        );

        setBounds(300, 140, 975, 575);
    }// </editor-fold>//GEN-END:initComponents
    
    JInternalFrame o = new JInternalFrame();

    public void limpiar(JInternalFrame j) {
        
        j.dispose();
    }
    
    private void menuItemAfiHabYDesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemAfiHabYDesActionPerformed
        AfiliadosAgregarOAnular afiAA = new AfiliadosAgregarOAnular();
        limpiar(o);
        o = afiAA;
        panelGradAfi.add(afiAA);
        afiAA.setVisible(true);
    }//GEN-LAST:event_menuItemAfiHabYDesActionPerformed

    private void menuItemAfiModActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemAfiModActionPerformed
        AfiliadosMod afimod = new AfiliadosMod();
        limpiar(o);
        o = afimod;
        panelGradAfi.add(afimod);
        afimod.setVisible(true);
    }//GEN-LAST:event_menuItemAfiModActionPerformed

    private void menuItemAfiListaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemAfiListaActionPerformed
        AfiliadosLista afl = new AfiliadosLista();
        limpiar(o);
        o = afl;
        panelGradAfi.add(afl);
        afl.setVisible(true);
    }//GEN-LAST:event_menuItemAfiListaActionPerformed

    private void botonAtrasAfiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAtrasAfiActionPerformed
        dispose();
    }//GEN-LAST:event_botonAtrasAfiActionPerformed

    private void menuAfiListaAfiMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuAfiListaAfiMouseEntered
        setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_menuAfiListaAfiMouseEntered

    private void menuAfiListaAfiMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuAfiListaAfiMouseExited
        setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_menuAfiListaAfiMouseExited

    private void menuAfiHabiODeshAfiMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuAfiHabiODeshAfiMouseEntered
        setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_menuAfiHabiODeshAfiMouseEntered

    private void menuAfiHabiODeshAfiMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuAfiHabiODeshAfiMouseExited
        setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_menuAfiHabiODeshAfiMouseExited

    private void menuAfiModMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuAfiModMouseEntered
        setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_menuAfiModMouseEntered

    private void menuAfiModMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuAfiModMouseExited
        setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_menuAfiModMouseExited

    private void botonAtrasAfiMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonAtrasAfiMouseEntered
        setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_botonAtrasAfiMouseEntered

    private void botonAtrasAfiMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonAtrasAfiMouseExited
        setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_botonAtrasAfiMouseExited

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonAtrasAfi;
    private javax.swing.JMenuBar menuAfi;
    private javax.swing.JMenu menuAfiHabiODeshAfi;
    private javax.swing.JMenu menuAfiListaAfi;
    private javax.swing.JMenu menuAfiMod;
    private javax.swing.JMenuItem menuItemAfiHabYDes;
    private javax.swing.JMenuItem menuItemAfiLista;
    private javax.swing.JMenuItem menuItemAfiMod;
    private keeptoo.KGradientPanel panelGradAfi;
    // End of variables declaration//GEN-END:variables
}