
package ProjectoFinalSalud.Vistas;

import java.awt.Cursor;
import javax.swing.JInternalFrame;
import javax.swing.plaf.basic.BasicInternalFrameUI;

public class Especialidades extends javax.swing.JInternalFrame {

    public Especialidades() {
        
        initComponents();
        
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        BasicInternalFrameUI bui = (BasicInternalFrameUI) this.getUI();
        bui.setNorthPane(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelGradEsp = new keeptoo.KGradientPanel();
        botonAtrasEsp = new javax.swing.JButton();
        menuEsp = new javax.swing.JMenuBar();
        menuEspListaEsp = new javax.swing.JMenu();
        menuItemEspListaProfXEsp = new javax.swing.JMenuItem();
        menuEspAgreEsp = new javax.swing.JMenu();
        menuItemEspAgreEsp = new javax.swing.JMenuItem();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(975, 575));

        panelGradEsp.setBackground(new java.awt.Color(255, 255, 255));
        panelGradEsp.setkEndColor(new java.awt.Color(0, 153, 255));
        panelGradEsp.setkStartColor(new java.awt.Color(0, 153, 0));
        panelGradEsp.setPreferredSize(new java.awt.Dimension(975, 575));

        botonAtrasEsp.setBackground(new java.awt.Color(255, 255, 255));
        botonAtrasEsp.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        botonAtrasEsp.setForeground(new java.awt.Color(255, 255, 255));
        botonAtrasEsp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagenesDelProyecto/BotonRetroceso.png"))); // NOI18N
        botonAtrasEsp.setText("Atrás");
        botonAtrasEsp.setBorderPainted(false);
        botonAtrasEsp.setContentAreaFilled(false);
        botonAtrasEsp.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        botonAtrasEsp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botonAtrasEspMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botonAtrasEspMouseExited(evt);
            }
        });
        botonAtrasEsp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAtrasEspActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelGradEspLayout = new javax.swing.GroupLayout(panelGradEsp);
        panelGradEsp.setLayout(panelGradEspLayout);
        panelGradEspLayout.setHorizontalGroup(
            panelGradEspLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelGradEspLayout.createSequentialGroup()
                .addContainerGap(796, Short.MAX_VALUE)
                .addComponent(botonAtrasEsp)
                .addContainerGap())
        );
        panelGradEspLayout.setVerticalGroup(
            panelGradEspLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelGradEspLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(botonAtrasEsp)
                .addContainerGap(460, Short.MAX_VALUE))
        );

        menuEspListaEsp.setBackground(new java.awt.Color(255, 255, 255));
        menuEspListaEsp.setText("Lista De Especialidades");
        menuEspListaEsp.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        menuEspListaEsp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                menuEspListaEspMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                menuEspListaEspMouseExited(evt);
            }
        });

        menuItemEspListaProfXEsp.setBackground(new java.awt.Color(255, 255, 255));
        menuItemEspListaProfXEsp.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        menuItemEspListaProfXEsp.setText("Profesionales Por Especialidad");
        menuItemEspListaProfXEsp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemEspListaProfXEspActionPerformed(evt);
            }
        });
        menuEspListaEsp.add(menuItemEspListaProfXEsp);

        menuEsp.add(menuEspListaEsp);

        menuEspAgreEsp.setBackground(new java.awt.Color(255, 255, 255));
        menuEspAgreEsp.setText("Agregar Una Especialidad");
        menuEspAgreEsp.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        menuEspAgreEsp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                menuEspAgreEspMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                menuEspAgreEspMouseExited(evt);
            }
        });

        menuItemEspAgreEsp.setBackground(new java.awt.Color(255, 255, 255));
        menuItemEspAgreEsp.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        menuItemEspAgreEsp.setText("Agregar Una Especialidad");
        menuItemEspAgreEsp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemEspAgreEspActionPerformed(evt);
            }
        });
        menuEspAgreEsp.add(menuItemEspAgreEsp);

        menuEsp.add(menuEspAgreEsp);

        setJMenuBar(menuEsp);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelGradEsp, javax.swing.GroupLayout.DEFAULT_SIZE, 959, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelGradEsp, javax.swing.GroupLayout.DEFAULT_SIZE, 524, Short.MAX_VALUE)
        );

        setBounds(300, 140, 975, 575);
    }// </editor-fold>//GEN-END:initComponents

    JInternalFrame o = new JInternalFrame();

    public void limpiar(JInternalFrame j) {
        
        j.dispose();
    }
    
    private void menuItemEspAgreEspActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemEspAgreEspActionPerformed
        EspecialidadesAgregar ea = new EspecialidadesAgregar();
        limpiar(o);
        o = ea;
        panelGradEsp.add(ea);
        ea.setVisible(true);
    }//GEN-LAST:event_menuItemEspAgreEspActionPerformed

    private void botonAtrasEspActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAtrasEspActionPerformed
        dispose();
    }//GEN-LAST:event_botonAtrasEspActionPerformed

    private void menuItemEspListaProfXEspActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemEspListaProfXEspActionPerformed
        EspecialidadesLista ed = new EspecialidadesLista();
        limpiar(o);
        o = ed;
        panelGradEsp.add(ed);
        ed.setVisible(true);
    }//GEN-LAST:event_menuItemEspListaProfXEspActionPerformed

    private void menuEspListaEspMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuEspListaEspMouseEntered
        setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_menuEspListaEspMouseEntered

    private void menuEspListaEspMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuEspListaEspMouseExited
        setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_menuEspListaEspMouseExited

    private void menuEspAgreEspMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuEspAgreEspMouseEntered
        setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_menuEspAgreEspMouseEntered

    private void menuEspAgreEspMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuEspAgreEspMouseExited
        setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_menuEspAgreEspMouseExited

    private void botonAtrasEspMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonAtrasEspMouseEntered
        setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_botonAtrasEspMouseEntered

    private void botonAtrasEspMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonAtrasEspMouseExited
        setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_botonAtrasEspMouseExited

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonAtrasEsp;
    private javax.swing.JMenuBar menuEsp;
    private javax.swing.JMenu menuEspAgreEsp;
    private javax.swing.JMenu menuEspListaEsp;
    private javax.swing.JMenuItem menuItemEspAgreEsp;
    private javax.swing.JMenuItem menuItemEspListaProfXEsp;
    private keeptoo.KGradientPanel panelGradEsp;
    // End of variables declaration//GEN-END:variables
}