package ProjectoFinalSalud.Vistas;

import ProjectoFinalSalud.AccesoDeDatos.UsuarioData;
import java.awt.Component;
import java.awt.Cursor;
import javax.swing.JInternalFrame;

public class Inicio extends javax.swing.JFrame {

    UsuarioData usuaData = new UsuarioData();
    
    public Inicio() {

        initComponents();
        setTitle("MásSalud");
        Bloquear();
    }
    
    JInternalFrame o = new JInternalFrame();

    public void limpiar(JInternalFrame j) {
        
        j.dispose();
    }
    
    public void Bloquear() {

        for (Component a : panelGradBotPrincipales.getComponents()) {
            a.setEnabled(false);
            botonCerrSes.setVisible(false);
            etiquetaBienvenido.setVisible(false);
            botonRegistro.setVisible(true);
            botonIniSes.setVisible(true); 
        }
    }

    public void Desbloquear() {

        for (Component b : panelGradBotPrincipales.getComponents()) {
            b.setEnabled(true);
            botonCerrSes.setVisible(true);
            etiquetaBienvenido.setVisible(true);
            etiquetaBienvenido.setText("Bienvenido");
            botonRegistro.setVisible(false);
            botonIniSes.setVisible(false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelEscritorio = new javax.swing.JDesktopPane();
        panelGradPrincipal = new keeptoo.KGradientPanel();
        etiquetaLogoPrincipal = new javax.swing.JLabel();
        etiquetaBienvenido = new javax.swing.JLabel();
        etiquetaPropaganda = new javax.swing.JLabel();
        separadorMenuPrincipal1 = new javax.swing.JSeparator();
        botonRegistro = new javax.swing.JButton();
        botonIniSes = new javax.swing.JButton();
        botonCerrSes = new javax.swing.JButton();
        panelGradBotPrincipales = new keeptoo.KGradientPanel();
        botonMenuDesplegable1 = new javax.swing.JButton();
        botonMenuDesplegable2 = new javax.swing.JButton();
        botonMenuDesplegable3 = new javax.swing.JButton();
        botonMenuDesplegable4 = new javax.swing.JButton();
        botonMenuDesplegable5 = new javax.swing.JButton();
        botonMenuDesplegable6 = new javax.swing.JButton();
        etiquetaMenuDesplegable1 = new javax.swing.JLabel();
        etiquetaMenuDesplegable2 = new javax.swing.JLabel();
        etiquetaMenuDesplegable3 = new javax.swing.JLabel();
        etiquetaMenuDesplegable4 = new javax.swing.JLabel();
        etiquetaMenuDesplegable5 = new javax.swing.JLabel();
        etiquetaMenuDesplegable6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        panelEscritorio.setBackground(new java.awt.Color(255, 255, 255));

        panelGradPrincipal.setBackground(new java.awt.Color(255, 255, 255));
        panelGradPrincipal.setkEndColor(new java.awt.Color(0, 153, 255));
        panelGradPrincipal.setkStartColor(new java.awt.Color(0, 153, 0));

        etiquetaLogoPrincipal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagenesDelProyecto/MasSaludLogo.png"))); // NOI18N

        etiquetaBienvenido.setBackground(new java.awt.Color(255, 255, 255));
        etiquetaBienvenido.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        etiquetaBienvenido.setForeground(new java.awt.Color(255, 255, 255));

        etiquetaPropaganda.setBackground(new java.awt.Color(255, 255, 255));
        etiquetaPropaganda.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        etiquetaPropaganda.setForeground(new java.awt.Color(255, 255, 255));
        etiquetaPropaganda.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        etiquetaPropaganda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagenesDelProyecto/MarcoPropaganda0.png"))); // NOI18N

        separadorMenuPrincipal1.setForeground(new java.awt.Color(255, 255, 255));
        separadorMenuPrincipal1.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));

        botonRegistro.setBackground(new java.awt.Color(255, 255, 255));
        botonRegistro.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        botonRegistro.setForeground(new java.awt.Color(255, 255, 255));
        botonRegistro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagenesDelProyecto/BotonUsuarioRegis.png"))); // NOI18N
        botonRegistro.setToolTipText("");
        botonRegistro.setBorderPainted(false);
        botonRegistro.setContentAreaFilled(false);
        botonRegistro.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        botonRegistro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botonRegistroMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botonRegistroMouseExited(evt);
            }
        });
        botonRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonRegistroActionPerformed(evt);
            }
        });

        botonIniSes.setBackground(new java.awt.Color(255, 255, 255));
        botonIniSes.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        botonIniSes.setForeground(new java.awt.Color(255, 255, 255));
        botonIniSes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagenesDelProyecto/BotonUsuarioIniSes.png"))); // NOI18N
        botonIniSes.setBorderPainted(false);
        botonIniSes.setContentAreaFilled(false);
        botonIniSes.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        botonIniSes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botonIniSesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botonIniSesMouseExited(evt);
            }
        });
        botonIniSes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonIniSesActionPerformed(evt);
            }
        });

        botonCerrSes.setBackground(new java.awt.Color(255, 255, 255));
        botonCerrSes.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        botonCerrSes.setForeground(new java.awt.Color(255, 255, 255));
        botonCerrSes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagenesDelProyecto/BotonUsuarioCerrSes.png"))); // NOI18N
        botonCerrSes.setBorderPainted(false);
        botonCerrSes.setContentAreaFilled(false);
        botonCerrSes.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        botonCerrSes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botonCerrSesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botonCerrSesMouseExited(evt);
            }
        });
        botonCerrSes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCerrSesActionPerformed(evt);
            }
        });

        panelGradBotPrincipales.setBackground(new java.awt.Color(255, 255, 255));
        panelGradBotPrincipales.setkEndColor(new java.awt.Color(0, 153, 255));
        panelGradBotPrincipales.setkStartColor(new java.awt.Color(204, 255, 255));

        botonMenuDesplegable1.setBackground(panelGradPrincipal.getkStartColor());
        botonMenuDesplegable1.setFont(new java.awt.Font("Verdana", 3, 14)); // NOI18N
        botonMenuDesplegable1.setForeground(new java.awt.Color(255, 255, 255));
        botonMenuDesplegable1.setText("Ordenes");
        botonMenuDesplegable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botonMenuDesplegable1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botonMenuDesplegable1MouseExited(evt);
            }
        });
        botonMenuDesplegable1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonMenuDesplegable1ActionPerformed(evt);
            }
        });

        botonMenuDesplegable2.setBackground(panelGradPrincipal.getkStartColor());
        botonMenuDesplegable2.setFont(new java.awt.Font("Verdana", 3, 14)); // NOI18N
        botonMenuDesplegable2.setForeground(new java.awt.Color(255, 255, 255));
        botonMenuDesplegable2.setText("Consultas");
        botonMenuDesplegable2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botonMenuDesplegable2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botonMenuDesplegable2MouseExited(evt);
            }
        });
        botonMenuDesplegable2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonMenuDesplegable2ActionPerformed(evt);
            }
        });

        botonMenuDesplegable3.setBackground(panelGradPrincipal.getkStartColor());
        botonMenuDesplegable3.setFont(new java.awt.Font("Verdana", 3, 14)); // NOI18N
        botonMenuDesplegable3.setForeground(new java.awt.Color(255, 255, 255));
        botonMenuDesplegable3.setText("Especialidades");
        botonMenuDesplegable3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botonMenuDesplegable3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botonMenuDesplegable3MouseExited(evt);
            }
        });
        botonMenuDesplegable3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonMenuDesplegable3ActionPerformed(evt);
            }
        });

        botonMenuDesplegable4.setBackground(panelGradPrincipal.getkStartColor());
        botonMenuDesplegable4.setFont(new java.awt.Font("Verdana", 3, 14)); // NOI18N
        botonMenuDesplegable4.setForeground(new java.awt.Color(255, 255, 255));
        botonMenuDesplegable4.setText("Profesionales");
        botonMenuDesplegable4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botonMenuDesplegable4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botonMenuDesplegable4MouseExited(evt);
            }
        });
        botonMenuDesplegable4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonMenuDesplegable4ActionPerformed(evt);
            }
        });

        botonMenuDesplegable5.setBackground(panelGradPrincipal.getkStartColor());
        botonMenuDesplegable5.setFont(new java.awt.Font("Verdana", 3, 14)); // NOI18N
        botonMenuDesplegable5.setForeground(new java.awt.Color(255, 255, 255));
        botonMenuDesplegable5.setText("Afiliados");
        botonMenuDesplegable5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botonMenuDesplegable5MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botonMenuDesplegable5MouseExited(evt);
            }
        });
        botonMenuDesplegable5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonMenuDesplegable5ActionPerformed(evt);
            }
        });

        botonMenuDesplegable6.setBackground(panelGradPrincipal.getkStartColor());
        botonMenuDesplegable6.setFont(new java.awt.Font("Verdana", 3, 14)); // NOI18N
        botonMenuDesplegable6.setForeground(new java.awt.Color(255, 255, 255));
        botonMenuDesplegable6.setText("Más Informacion");
        botonMenuDesplegable6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botonMenuDesplegable6MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botonMenuDesplegable6MouseExited(evt);
            }
        });
        botonMenuDesplegable6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonMenuDesplegable6ActionPerformed(evt);
            }
        });

        etiquetaMenuDesplegable1.setBackground(new java.awt.Color(255, 255, 255));
        etiquetaMenuDesplegable1.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        etiquetaMenuDesplegable1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagenesDelProyecto/OrdenDeConsultaIcono.png"))); // NOI18N

        etiquetaMenuDesplegable2.setBackground(new java.awt.Color(255, 255, 255));
        etiquetaMenuDesplegable2.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        etiquetaMenuDesplegable2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagenesDelProyecto/ConsultasIcono.png"))); // NOI18N

        etiquetaMenuDesplegable3.setBackground(new java.awt.Color(255, 255, 255));
        etiquetaMenuDesplegable3.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        etiquetaMenuDesplegable3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagenesDelProyecto/ProfesionalesIcono.png"))); // NOI18N

        etiquetaMenuDesplegable4.setBackground(new java.awt.Color(255, 255, 255));
        etiquetaMenuDesplegable4.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        etiquetaMenuDesplegable4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagenesDelProyecto/AfiliadoIcono.png"))); // NOI18N

        etiquetaMenuDesplegable5.setBackground(new java.awt.Color(255, 255, 255));
        etiquetaMenuDesplegable5.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        etiquetaMenuDesplegable5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagenesDelProyecto/MasInformacionIcono.png"))); // NOI18N

        etiquetaMenuDesplegable6.setBackground(new java.awt.Color(255, 255, 255));
        etiquetaMenuDesplegable6.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        etiquetaMenuDesplegable6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagenesDelProyecto/EspecialidadesIcono.png"))); // NOI18N

        javax.swing.GroupLayout panelGradBotPrincipalesLayout = new javax.swing.GroupLayout(panelGradBotPrincipales);
        panelGradBotPrincipales.setLayout(panelGradBotPrincipalesLayout);
        panelGradBotPrincipalesLayout.setHorizontalGroup(
            panelGradBotPrincipalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelGradBotPrincipalesLayout.createSequentialGroup()
                .addComponent(etiquetaMenuDesplegable1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botonMenuDesplegable1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(panelGradBotPrincipalesLayout.createSequentialGroup()
                .addComponent(etiquetaMenuDesplegable4, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botonMenuDesplegable5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(panelGradBotPrincipalesLayout.createSequentialGroup()
                .addComponent(etiquetaMenuDesplegable2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botonMenuDesplegable2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(panelGradBotPrincipalesLayout.createSequentialGroup()
                .addComponent(etiquetaMenuDesplegable6, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botonMenuDesplegable3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(panelGradBotPrincipalesLayout.createSequentialGroup()
                .addComponent(etiquetaMenuDesplegable3, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botonMenuDesplegable4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelGradBotPrincipalesLayout.createSequentialGroup()
                .addComponent(etiquetaMenuDesplegable5, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botonMenuDesplegable6, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE))
        );
        panelGradBotPrincipalesLayout.setVerticalGroup(
            panelGradBotPrincipalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelGradBotPrincipalesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelGradBotPrincipalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(botonMenuDesplegable1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(etiquetaMenuDesplegable1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelGradBotPrincipalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(etiquetaMenuDesplegable2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(botonMenuDesplegable2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelGradBotPrincipalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(botonMenuDesplegable3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(etiquetaMenuDesplegable6, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelGradBotPrincipalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(etiquetaMenuDesplegable3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(botonMenuDesplegable4, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelGradBotPrincipalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(etiquetaMenuDesplegable4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(botonMenuDesplegable5, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelGradBotPrincipalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(etiquetaMenuDesplegable5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(botonMenuDesplegable6, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(37, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panelGradPrincipalLayout = new javax.swing.GroupLayout(panelGradPrincipal);
        panelGradPrincipal.setLayout(panelGradPrincipalLayout);
        panelGradPrincipalLayout.setHorizontalGroup(
            panelGradPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelGradPrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(etiquetaLogoPrincipal)
                .addGap(43, 43, 43)
                .addComponent(etiquetaBienvenido, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 458, Short.MAX_VALUE)
                .addComponent(botonCerrSes)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botonRegistro)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botonIniSes)
                .addContainerGap())
            .addComponent(separadorMenuPrincipal1)
            .addGroup(panelGradPrincipalLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(panelGradBotPrincipales, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addComponent(etiquetaPropaganda)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelGradPrincipalLayout.setVerticalGroup(
            panelGradPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelGradPrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelGradPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botonIniSes)
                    .addComponent(etiquetaLogoPrincipal)
                    .addComponent(botonRegistro)
                    .addComponent(etiquetaBienvenido, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonCerrSes))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(separadorMenuPrincipal1, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(panelGradPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelGradPrincipalLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                        .addComponent(panelGradBotPrincipales, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(84, 84, 84))
                    .addGroup(panelGradPrincipalLayout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addComponent(etiquetaPropaganda)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        panelEscritorio.setLayer(panelGradPrincipal, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout panelEscritorioLayout = new javax.swing.GroupLayout(panelEscritorio);
        panelEscritorio.setLayout(panelEscritorioLayout);
        panelEscritorioLayout.setHorizontalGroup(
            panelEscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelGradPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panelEscritorioLayout.setVerticalGroup(
            panelEscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelGradPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelEscritorio)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelEscritorio)
        );

        setSize(new java.awt.Dimension(1296, 759));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void botonRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonRegistroActionPerformed
        Registrarse Regis = new Registrarse();
        panelEscritorio.add(Regis);
        Regis.setVisible(true);
    }//GEN-LAST:event_botonRegistroActionPerformed

    private void botonIniSesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonIniSesActionPerformed
        IniciarSesion InSe = new IniciarSesion();
        panelEscritorio.add(InSe);
        InSe.setVisible(true);
        Desbloquear();
    }//GEN-LAST:event_botonIniSesActionPerformed

    private void botonMenuDesplegable1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonMenuDesplegable1ActionPerformed
        Ordenes ord = new Ordenes();
        limpiar(o);
        o = ord;
        panelEscritorio.add(ord);
        ord.setVisible(true);
    }//GEN-LAST:event_botonMenuDesplegable1ActionPerformed

    private void botonMenuDesplegable2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonMenuDesplegable2ActionPerformed
        Consultas consu = new Consultas();
        limpiar(o);
        o = consu;
        panelEscritorio.add(consu);
        consu.setVisible(true);
    }//GEN-LAST:event_botonMenuDesplegable2ActionPerformed

    private void botonMenuDesplegable3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonMenuDesplegable3ActionPerformed
        Especialidades espe = new Especialidades();
        limpiar(o);
        o = espe;
        panelEscritorio.add(espe);
        espe.setVisible(true);
    }//GEN-LAST:event_botonMenuDesplegable3ActionPerformed

    private void botonMenuDesplegable4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonMenuDesplegable4ActionPerformed
        Profesionales prof = new Profesionales();
        limpiar(o);
        o = prof;
        panelEscritorio.add(prof);
        prof.setVisible(true);
    }//GEN-LAST:event_botonMenuDesplegable4ActionPerformed

    private void botonMenuDesplegable5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonMenuDesplegable5ActionPerformed
        Afiliados afil = new Afiliados();
        limpiar(o);
        o = afil;
        panelEscritorio.add(afil);
        afil.setVisible(true);
    }//GEN-LAST:event_botonMenuDesplegable5ActionPerformed

    private void botonMenuDesplegable6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonMenuDesplegable6ActionPerformed
        MasInformacion msInfo = new MasInformacion();
        limpiar(o);
        o = msInfo;
        panelEscritorio.add(msInfo);
        msInfo.setVisible(true);
    }//GEN-LAST:event_botonMenuDesplegable6ActionPerformed

    private void botonCerrSesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCerrSesActionPerformed
        Bloquear();
    }//GEN-LAST:event_botonCerrSesActionPerformed

    private void botonIniSesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonIniSesMouseEntered
        setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_botonIniSesMouseEntered

    private void botonIniSesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonIniSesMouseExited
        setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_botonIniSesMouseExited

    private void botonRegistroMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonRegistroMouseEntered
        setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_botonRegistroMouseEntered

    private void botonRegistroMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonRegistroMouseExited
        setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_botonRegistroMouseExited

    private void botonCerrSesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonCerrSesMouseEntered
        setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_botonCerrSesMouseEntered

    private void botonCerrSesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonCerrSesMouseExited
        setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_botonCerrSesMouseExited

    private void botonMenuDesplegable1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonMenuDesplegable1MouseEntered
        setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_botonMenuDesplegable1MouseEntered

    private void botonMenuDesplegable1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonMenuDesplegable1MouseExited
        setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_botonMenuDesplegable1MouseExited

    private void botonMenuDesplegable2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonMenuDesplegable2MouseEntered
        setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_botonMenuDesplegable2MouseEntered

    private void botonMenuDesplegable2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonMenuDesplegable2MouseExited
        setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_botonMenuDesplegable2MouseExited

    private void botonMenuDesplegable3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonMenuDesplegable3MouseEntered
        setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_botonMenuDesplegable3MouseEntered

    private void botonMenuDesplegable3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonMenuDesplegable3MouseExited
        setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_botonMenuDesplegable3MouseExited

    private void botonMenuDesplegable4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonMenuDesplegable4MouseEntered
        setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_botonMenuDesplegable4MouseEntered

    private void botonMenuDesplegable4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonMenuDesplegable4MouseExited
        setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_botonMenuDesplegable4MouseExited

    private void botonMenuDesplegable5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonMenuDesplegable5MouseEntered
        setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_botonMenuDesplegable5MouseEntered

    private void botonMenuDesplegable5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonMenuDesplegable5MouseExited
        setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_botonMenuDesplegable5MouseExited

    private void botonMenuDesplegable6MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonMenuDesplegable6MouseEntered
        setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_botonMenuDesplegable6MouseEntered

    private void botonMenuDesplegable6MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonMenuDesplegable6MouseExited
        setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_botonMenuDesplegable6MouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Inicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonCerrSes;
    private javax.swing.JButton botonIniSes;
    private javax.swing.JButton botonMenuDesplegable1;
    private javax.swing.JButton botonMenuDesplegable2;
    private javax.swing.JButton botonMenuDesplegable3;
    private javax.swing.JButton botonMenuDesplegable4;
    private javax.swing.JButton botonMenuDesplegable5;
    private javax.swing.JButton botonMenuDesplegable6;
    private javax.swing.JButton botonRegistro;
    private javax.swing.JLabel etiquetaBienvenido;
    private javax.swing.JLabel etiquetaLogoPrincipal;
    private javax.swing.JLabel etiquetaMenuDesplegable1;
    private javax.swing.JLabel etiquetaMenuDesplegable2;
    private javax.swing.JLabel etiquetaMenuDesplegable3;
    private javax.swing.JLabel etiquetaMenuDesplegable4;
    private javax.swing.JLabel etiquetaMenuDesplegable5;
    private javax.swing.JLabel etiquetaMenuDesplegable6;
    public javax.swing.JLabel etiquetaPropaganda;
    private javax.swing.JDesktopPane panelEscritorio;
    private keeptoo.KGradientPanel panelGradBotPrincipales;
    private keeptoo.KGradientPanel panelGradPrincipal;
    private javax.swing.JSeparator separadorMenuPrincipal1;
    // End of variables declaration//GEN-END:variables
}