
package ProjectoFinalSalud.Vistas;

import javax.swing.plaf.basic.BasicInternalFrameUI;

public class MasInformacionPrueba extends javax.swing.JInternalFrame {

    public MasInformacionPrueba() {
        
        initComponents();
        
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        BasicInternalFrameUI bui = (BasicInternalFrameUI) this.getUI();
        bui.setNorthPane(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botonAtrasMsInfoPrue = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(975, 575));

        botonAtrasMsInfoPrue.setBackground(new java.awt.Color(255, 255, 255));
        botonAtrasMsInfoPrue.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        botonAtrasMsInfoPrue.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagenesDelProyecto/BotonRetroceso.png"))); // NOI18N
        botonAtrasMsInfoPrue.setText("Atrás");
        botonAtrasMsInfoPrue.setBorderPainted(false);
        botonAtrasMsInfoPrue.setContentAreaFilled(false);
        botonAtrasMsInfoPrue.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        botonAtrasMsInfoPrue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAtrasMsInfoPrueActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(796, Short.MAX_VALUE)
                .addComponent(botonAtrasMsInfoPrue)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(botonAtrasMsInfoPrue)
                .addContainerGap(481, Short.MAX_VALUE))
        );

        setBounds(0, 0, 975, 575);
    }// </editor-fold>//GEN-END:initComponents

    private void botonAtrasMsInfoPrueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAtrasMsInfoPrueActionPerformed
        dispose();
    }//GEN-LAST:event_botonAtrasMsInfoPrueActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonAtrasMsInfoPrue;
    // End of variables declaration//GEN-END:variables
}