
package ProjectoFinalSalud.Vistas;

import java.awt.Color;
import javax.swing.plaf.basic.BasicInternalFrameUI;

public class MasInformacion extends javax.swing.JInternalFrame {

    public MasInformacion() {
        
        initComponents();
        
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        BasicInternalFrameUI bui = (BasicInternalFrameUI) this.getUI();
        bui.setNorthPane(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelGradMsInfo = new keeptoo.KGradientPanel();
        botonAtrasMsInfo = new javax.swing.JButton();
        botonHola = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(975, 575));

        panelGradMsInfo.setBackground(new java.awt.Color(255, 255, 255));
        panelGradMsInfo.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        panelGradMsInfo.setkEndColor(new java.awt.Color(0, 153, 255));
        panelGradMsInfo.setkStartColor(new java.awt.Color(0, 153, 0));
        panelGradMsInfo.setPreferredSize(new java.awt.Dimension(975, 575));

        botonAtrasMsInfo.setBackground(new java.awt.Color(255, 255, 255));
        botonAtrasMsInfo.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        botonAtrasMsInfo.setForeground(new java.awt.Color(255, 255, 255));
        botonAtrasMsInfo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagenesDelProyecto/BotonRetroceso.png"))); // NOI18N
        botonAtrasMsInfo.setText("Atrás");
        botonAtrasMsInfo.setBorderPainted(false);
        botonAtrasMsInfo.setContentAreaFilled(false);
        botonAtrasMsInfo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        botonAtrasMsInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAtrasMsInfoActionPerformed(evt);
            }
        });

        botonHola.setBackground(new java.awt.Color(0, 0, 255));
        botonHola.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        botonHola.setForeground(new java.awt.Color(255, 255, 255));
        botonHola.setText("HOLA");
        botonHola.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botonHolaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botonHolaMouseExited(evt);
            }
        });
        botonHola.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonHolaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelGradMsInfoLayout = new javax.swing.GroupLayout(panelGradMsInfo);
        panelGradMsInfo.setLayout(panelGradMsInfoLayout);
        panelGradMsInfoLayout.setHorizontalGroup(
            panelGradMsInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelGradMsInfoLayout.createSequentialGroup()
                .addContainerGap(796, Short.MAX_VALUE)
                .addComponent(botonAtrasMsInfo)
                .addContainerGap())
            .addGroup(panelGradMsInfoLayout.createSequentialGroup()
                .addGap(343, 343, 343)
                .addComponent(botonHola, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelGradMsInfoLayout.setVerticalGroup(
            panelGradMsInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelGradMsInfoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(botonAtrasMsInfo)
                .addGap(158, 158, 158)
                .addComponent(botonHola, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(216, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelGradMsInfo, javax.swing.GroupLayout.DEFAULT_SIZE, 959, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelGradMsInfo, javax.swing.GroupLayout.DEFAULT_SIZE, 545, Short.MAX_VALUE)
        );

        setBounds(300, 140, 975, 575);
    }// </editor-fold>//GEN-END:initComponents

    private void botonAtrasMsInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAtrasMsInfoActionPerformed
        dispose();
    }//GEN-LAST:event_botonAtrasMsInfoActionPerformed

    private void botonHolaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonHolaActionPerformed
        panelGradMsInfo.removeAll();
        panelGradMsInfo.repaint();
        MasInformacionPrueba msInfoP = new MasInformacionPrueba();
        panelGradMsInfo.add(msInfoP);
        msInfoP.setVisible(true);
    }//GEN-LAST:event_botonHolaActionPerformed

    private void botonHolaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonHolaMouseEntered
        botonHola.setBackground(Color.cyan);
    }//GEN-LAST:event_botonHolaMouseEntered

    private void botonHolaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonHolaMouseExited
        botonHola.setBackground(new Color(0,0,255));
    }//GEN-LAST:event_botonHolaMouseExited

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonAtrasMsInfo;
    private javax.swing.JButton botonHola;
    private keeptoo.KGradientPanel panelGradMsInfo;
    // End of variables declaration//GEN-END:variables
}