
package ProjectoFinalSalud.Vistas;

import javax.swing.plaf.basic.BasicInternalFrameUI;

public class Ordenes extends javax.swing.JInternalFrame {

    public Ordenes() {
        
        initComponents();
        
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        BasicInternalFrameUI bui = (BasicInternalFrameUI) this.getUI();
        bui.setNorthPane(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelGradOrden = new keeptoo.KGradientPanel();
        botonAtrasOrden = new javax.swing.JButton();
        menuOrden = new javax.swing.JMenuBar();
        menuOrdenSacOrd = new javax.swing.JMenu();
        menuItemOrdenSacOrd = new javax.swing.JMenuItem();
        menuOrdenOrdenes = new javax.swing.JMenu();
        menuItemOrdenOrdXFecha = new javax.swing.JMenuItem();
        menuItemOrdenOrdXAfi = new javax.swing.JMenuItem();
        menuItemOrdenOrdXPres = new javax.swing.JMenuItem();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(975, 575));

        panelGradOrden.setBackground(new java.awt.Color(255, 255, 255));
        panelGradOrden.setkEndColor(new java.awt.Color(0, 153, 255));
        panelGradOrden.setkStartColor(new java.awt.Color(0, 153, 0));
        panelGradOrden.setPreferredSize(new java.awt.Dimension(975, 575));

        botonAtrasOrden.setBackground(new java.awt.Color(255, 255, 255));
        botonAtrasOrden.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        botonAtrasOrden.setForeground(new java.awt.Color(255, 255, 255));
        botonAtrasOrden.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagenesDelProyecto/BotonRetroceso.png"))); // NOI18N
        botonAtrasOrden.setText("Atrás");
        botonAtrasOrden.setBorderPainted(false);
        botonAtrasOrden.setContentAreaFilled(false);
        botonAtrasOrden.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        botonAtrasOrden.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAtrasOrdenActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelGradOrdenLayout = new javax.swing.GroupLayout(panelGradOrden);
        panelGradOrden.setLayout(panelGradOrdenLayout);
        panelGradOrdenLayout.setHorizontalGroup(
            panelGradOrdenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelGradOrdenLayout.createSequentialGroup()
                .addContainerGap(1081, Short.MAX_VALUE)
                .addComponent(botonAtrasOrden)
                .addContainerGap())
        );
        panelGradOrdenLayout.setVerticalGroup(
            panelGradOrdenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelGradOrdenLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(botonAtrasOrden)
                .addContainerGap(505, Short.MAX_VALUE))
        );

        menuOrdenSacOrd.setBackground(new java.awt.Color(255, 255, 255));
        menuOrdenSacOrd.setText("Sacar Orden");
        menuOrdenSacOrd.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N

        menuItemOrdenSacOrd.setBackground(new java.awt.Color(255, 255, 255));
        menuItemOrdenSacOrd.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        menuItemOrdenSacOrd.setText("Sacar Orden");
        menuItemOrdenSacOrd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemOrdenSacOrdActionPerformed(evt);
            }
        });
        menuOrdenSacOrd.add(menuItemOrdenSacOrd);

        menuOrden.add(menuOrdenSacOrd);

        menuOrdenOrdenes.setBackground(new java.awt.Color(255, 255, 255));
        menuOrdenOrdenes.setText("Ordenes");
        menuOrdenOrdenes.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N

        menuItemOrdenOrdXFecha.setBackground(new java.awt.Color(255, 255, 255));
        menuItemOrdenOrdXFecha.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        menuItemOrdenOrdXFecha.setText("Ordenes Por Fecha");
        menuItemOrdenOrdXFecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemOrdenOrdXFechaActionPerformed(evt);
            }
        });
        menuOrdenOrdenes.add(menuItemOrdenOrdXFecha);

        menuItemOrdenOrdXAfi.setBackground(new java.awt.Color(255, 255, 255));
        menuItemOrdenOrdXAfi.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        menuItemOrdenOrdXAfi.setText("Ordenes Por Afiliado");
        menuItemOrdenOrdXAfi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemOrdenOrdXAfiActionPerformed(evt);
            }
        });
        menuOrdenOrdenes.add(menuItemOrdenOrdXAfi);

        menuItemOrdenOrdXPres.setBackground(new java.awt.Color(255, 255, 255));
        menuItemOrdenOrdXPres.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        menuItemOrdenOrdXPres.setText("Ordenes Por Prestador");
        menuItemOrdenOrdXPres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemOrdenOrdXPresActionPerformed(evt);
            }
        });
        menuOrdenOrdenes.add(menuItemOrdenOrdXPres);

        menuOrden.add(menuOrdenOrdenes);

        setJMenuBar(menuOrden);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelGradOrden, javax.swing.GroupLayout.DEFAULT_SIZE, 959, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelGradOrden, javax.swing.GroupLayout.DEFAULT_SIZE, 524, Short.MAX_VALUE)
        );

        setBounds(300, 140, 975, 575);
    }// </editor-fold>//GEN-END:initComponents

    private void menuItemOrdenSacOrdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemOrdenSacOrdActionPerformed
        panelGradOrden.removeAll();
        panelGradOrden.repaint();
        OrdenesSacar sa = new OrdenesSacar();
        panelGradOrden.add(sa);
        sa.setVisible(true);
    }//GEN-LAST:event_menuItemOrdenSacOrdActionPerformed

    private void menuItemOrdenOrdXFechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemOrdenOrdXFechaActionPerformed
        panelGradOrden.removeAll();
        panelGradOrden.repaint();
        OrdenesPorFecha opf = new OrdenesPorFecha();
        panelGradOrden.add(opf);
        opf.setVisible(true);
    }//GEN-LAST:event_menuItemOrdenOrdXFechaActionPerformed

    private void menuItemOrdenOrdXAfiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemOrdenOrdXAfiActionPerformed
        panelGradOrden.removeAll();
        panelGradOrden.repaint();
        OrdenesPorAfiliado opa = new OrdenesPorAfiliado();
        panelGradOrden.add(opa);
        opa.setVisible(true);
    }//GEN-LAST:event_menuItemOrdenOrdXAfiActionPerformed

    private void menuItemOrdenOrdXPresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemOrdenOrdXPresActionPerformed
        panelGradOrden.removeAll();
        panelGradOrden.repaint();
        OrdenesPorPrestador opp = new OrdenesPorPrestador();
        panelGradOrden.add(opp);
        opp.setVisible(true);
    }//GEN-LAST:event_menuItemOrdenOrdXPresActionPerformed

    private void botonAtrasOrdenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAtrasOrdenActionPerformed
        dispose();
    }//GEN-LAST:event_botonAtrasOrdenActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonAtrasOrden;
    private javax.swing.JMenuItem menuItemOrdenOrdXAfi;
    private javax.swing.JMenuItem menuItemOrdenOrdXFecha;
    private javax.swing.JMenuItem menuItemOrdenOrdXPres;
    private javax.swing.JMenuItem menuItemOrdenSacOrd;
    private javax.swing.JMenuBar menuOrden;
    private javax.swing.JMenu menuOrdenOrdenes;
    private javax.swing.JMenu menuOrdenSacOrd;
    private keeptoo.KGradientPanel panelGradOrden;
    // End of variables declaration//GEN-END:variables
}