
package ProjectoFinalSalud.Vistas;

import java.awt.Cursor;
import javax.swing.plaf.basic.BasicInternalFrameUI;

public class Profesionales extends javax.swing.JInternalFrame {

    public Profesionales() {    
        
        initComponents();
        
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        BasicInternalFrameUI bui = (BasicInternalFrameUI) this.getUI();
        bui.setNorthPane(null);
    }
      
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelGradProf = new keeptoo.KGradientPanel();
        botonAtrasProf = new javax.swing.JButton();
        menuProf = new javax.swing.JMenuBar();
        menuProfConsulta = new javax.swing.JMenu();
        menuItemConsul = new javax.swing.JMenuItem();
        menuProfAgreQuit = new javax.swing.JMenu();
        menuItemAdherir = new javax.swing.JMenuItem();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(975, 575));

        panelGradProf.setBackground(new java.awt.Color(255, 255, 255));
        panelGradProf.setkEndColor(new java.awt.Color(0, 153, 255));
        panelGradProf.setkStartColor(new java.awt.Color(0, 153, 0));
        panelGradProf.setPreferredSize(new java.awt.Dimension(975, 575));

        botonAtrasProf.setBackground(new java.awt.Color(255, 255, 255));
        botonAtrasProf.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        botonAtrasProf.setForeground(new java.awt.Color(255, 255, 255));
        botonAtrasProf.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagenesDelProyecto/BotonRetroceso.png"))); // NOI18N
        botonAtrasProf.setText("Atrás");
        botonAtrasProf.setBorderPainted(false);
        botonAtrasProf.setContentAreaFilled(false);
        botonAtrasProf.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        botonAtrasProf.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botonAtrasProfMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botonAtrasProfMouseExited(evt);
            }
        });
        botonAtrasProf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAtrasProfActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelGradProfLayout = new javax.swing.GroupLayout(panelGradProf);
        panelGradProf.setLayout(panelGradProfLayout);
        panelGradProfLayout.setHorizontalGroup(
            panelGradProfLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelGradProfLayout.createSequentialGroup()
                .addContainerGap(796, Short.MAX_VALUE)
                .addComponent(botonAtrasProf)
                .addContainerGap())
        );
        panelGradProfLayout.setVerticalGroup(
            panelGradProfLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelGradProfLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(botonAtrasProf)
                .addContainerGap(460, Short.MAX_VALUE))
        );

        menuProfConsulta.setBackground(new java.awt.Color(255, 255, 255));
        menuProfConsulta.setText("Consulta Nuestra Lista De Profesionales");
        menuProfConsulta.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        menuProfConsulta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                menuProfConsultaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                menuProfConsultaMouseExited(evt);
            }
        });

        menuItemConsul.setBackground(new java.awt.Color(255, 255, 255));
        menuItemConsul.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        menuItemConsul.setText("Consultar Lista");
        menuItemConsul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemConsulActionPerformed(evt);
            }
        });
        menuProfConsulta.add(menuItemConsul);

        menuProf.add(menuProfConsulta);

        menuProfAgreQuit.setBackground(new java.awt.Color(255, 255, 255));
        menuProfAgreQuit.setText("Adherir Profesionales");
        menuProfAgreQuit.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        menuProfAgreQuit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                menuProfAgreQuitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                menuProfAgreQuitMouseExited(evt);
            }
        });

        menuItemAdherir.setBackground(new java.awt.Color(255, 255, 255));
        menuItemAdherir.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        menuItemAdherir.setText("Adherir Profesionales");
        menuItemAdherir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemAdherirActionPerformed(evt);
            }
        });
        menuProfAgreQuit.add(menuItemAdherir);

        menuProf.add(menuProfAgreQuit);

        setJMenuBar(menuProf);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelGradProf, javax.swing.GroupLayout.DEFAULT_SIZE, 959, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelGradProf, javax.swing.GroupLayout.DEFAULT_SIZE, 524, Short.MAX_VALUE)
        );

        setBounds(300, 140, 975, 575);
    }// </editor-fold>//GEN-END:initComponents

    private void menuItemConsulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemConsulActionPerformed
       panelGradProf.removeAll();
       panelGradProf.repaint();
       ProfesionalesConsultas profCon = new ProfesionalesConsultas();
       panelGradProf.add(profCon);
       profCon.setVisible(true);
    }//GEN-LAST:event_menuItemConsulActionPerformed

    private void menuItemAdherirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemAdherirActionPerformed
       panelGradProf.removeAll();
       panelGradProf.repaint();
       ProfesionalesAgregarQuitar profAQ = new ProfesionalesAgregarQuitar();
       panelGradProf.add(profAQ);
       profAQ.setVisible(true);
    }//GEN-LAST:event_menuItemAdherirActionPerformed

    private void botonAtrasProfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAtrasProfActionPerformed
        dispose();
    }//GEN-LAST:event_botonAtrasProfActionPerformed

    private void menuProfConsultaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuProfConsultaMouseEntered
        setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_menuProfConsultaMouseEntered

    private void menuProfConsultaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuProfConsultaMouseExited
        setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_menuProfConsultaMouseExited

    private void menuProfAgreQuitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuProfAgreQuitMouseEntered
        setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_menuProfAgreQuitMouseEntered

    private void menuProfAgreQuitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuProfAgreQuitMouseExited
        setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_menuProfAgreQuitMouseExited

    private void botonAtrasProfMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonAtrasProfMouseEntered
        setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_botonAtrasProfMouseEntered

    private void botonAtrasProfMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonAtrasProfMouseExited
        setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_botonAtrasProfMouseExited

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonAtrasProf;
    private javax.swing.JMenuItem menuItemAdherir;
    private javax.swing.JMenuItem menuItemConsul;
    private javax.swing.JMenuBar menuProf;
    private javax.swing.JMenu menuProfAgreQuit;
    private javax.swing.JMenu menuProfConsulta;
    private keeptoo.KGradientPanel panelGradProf;
    // End of variables declaration//GEN-END:variables
}