
package ProjectoFinalSalud.Vistas;

import ProjectoFinalSalud.AccesoDeDatos.PrestadorData;
import ProjectoFinalSalud.Entidades.Prestador;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.plaf.basic.BasicInternalFrameUI;

public class ProfesionalesAgregarQuitar extends javax.swing.JInternalFrame {

    PrestadorData presData = new PrestadorData();
    
    public ProfesionalesAgregarQuitar() {
        
        initComponents();
        
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        BasicInternalFrameUI bui = (BasicInternalFrameUI) this.getUI();
        bui.setNorthPane(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelGradProfAgreQuit = new keeptoo.KGradientPanel();
        etiquetaProfAgreQuit = new javax.swing.JLabel();
        etiquetaProfAgreQuitDni = new javax.swing.JLabel();
        etiquetaProfAgreQuitNomYApe = new javax.swing.JLabel();
        etiquetaProfAgreQuitNumTel = new javax.swing.JLabel();
        etiquetaProfAgreQuitDom = new javax.swing.JLabel();
        etiquetaProfAgreQuitEstado = new javax.swing.JLabel();
        etiquetaProfAgreQuitAcONoac = new javax.swing.JLabel();
        textoProfAgreQuitDni = new javax.swing.JTextField();
        textoProfAgreQuitNomYApe = new javax.swing.JTextField();
        textoProfAgreQuitNumTel = new javax.swing.JTextField();
        textoProfAgreQuitDom = new javax.swing.JTextField();
        separadorProfAgreQuit = new javax.swing.JSeparator();
        botonProfAgreQuitBuscar = new javax.swing.JButton();
        botonProfAgreQuitRein = new javax.swing.JButton();
        botonProfAgreQuitGuardar = new javax.swing.JButton();
        botonProfAgreQuitAnular = new javax.swing.JButton();
        botonAtrasProfAgreQuit = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(975, 575));

        panelGradProfAgreQuit.setBackground(new java.awt.Color(255, 255, 255));
        panelGradProfAgreQuit.setkEndColor(new java.awt.Color(0, 153, 255));
        panelGradProfAgreQuit.setkStartColor(new java.awt.Color(0, 153, 0));
        panelGradProfAgreQuit.setPreferredSize(new java.awt.Dimension(975, 575));

        etiquetaProfAgreQuit.setBackground(new java.awt.Color(255, 255, 255));
        etiquetaProfAgreQuit.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        etiquetaProfAgreQuit.setForeground(new java.awt.Color(255, 255, 255));
        etiquetaProfAgreQuit.setText("Agregar Y Anular Profesionales");

        etiquetaProfAgreQuitDni.setBackground(new java.awt.Color(255, 255, 255));
        etiquetaProfAgreQuitDni.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        etiquetaProfAgreQuitDni.setForeground(new java.awt.Color(255, 255, 255));
        etiquetaProfAgreQuitDni.setText("Ingrese DNI Del Profesional:");

        etiquetaProfAgreQuitNomYApe.setBackground(new java.awt.Color(255, 255, 255));
        etiquetaProfAgreQuitNomYApe.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        etiquetaProfAgreQuitNomYApe.setForeground(new java.awt.Color(255, 255, 255));
        etiquetaProfAgreQuitNomYApe.setText("Nombre y Apellido:");

        etiquetaProfAgreQuitNumTel.setBackground(new java.awt.Color(255, 255, 255));
        etiquetaProfAgreQuitNumTel.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        etiquetaProfAgreQuitNumTel.setForeground(new java.awt.Color(255, 255, 255));
        etiquetaProfAgreQuitNumTel.setText("Número de Teléfono:");

        etiquetaProfAgreQuitDom.setBackground(new java.awt.Color(255, 255, 255));
        etiquetaProfAgreQuitDom.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        etiquetaProfAgreQuitDom.setForeground(new java.awt.Color(255, 255, 255));
        etiquetaProfAgreQuitDom.setText("Domicilio:");

        etiquetaProfAgreQuitEstado.setBackground(new java.awt.Color(255, 255, 255));
        etiquetaProfAgreQuitEstado.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        etiquetaProfAgreQuitEstado.setForeground(new java.awt.Color(255, 255, 255));
        etiquetaProfAgreQuitEstado.setText("Estado:");

        etiquetaProfAgreQuitAcONoac.setBackground(new java.awt.Color(255, 255, 255));
        etiquetaProfAgreQuitAcONoac.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        etiquetaProfAgreQuitAcONoac.setForeground(new java.awt.Color(255, 255, 255));

        textoProfAgreQuitDni.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N

        textoProfAgreQuitNomYApe.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N

        textoProfAgreQuitNumTel.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N

        textoProfAgreQuitDom.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N

        separadorProfAgreQuit.setForeground(new java.awt.Color(255, 255, 255));
        separadorProfAgreQuit.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));

        botonProfAgreQuitBuscar.setBackground(new java.awt.Color(255, 255, 255));
        botonProfAgreQuitBuscar.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        botonProfAgreQuitBuscar.setForeground(new java.awt.Color(255, 255, 255));
        botonProfAgreQuitBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagenesDelProyecto/Boton.png"))); // NOI18N
        botonProfAgreQuitBuscar.setText("Buscar");
        botonProfAgreQuitBuscar.setBorderPainted(false);
        botonProfAgreQuitBuscar.setContentAreaFilled(false);
        botonProfAgreQuitBuscar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        botonProfAgreQuitBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonProfAgreQuitBuscarActionPerformed(evt);
            }
        });

        botonProfAgreQuitRein.setBackground(new java.awt.Color(255, 255, 255));
        botonProfAgreQuitRein.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        botonProfAgreQuitRein.setForeground(new java.awt.Color(255, 255, 255));
        botonProfAgreQuitRein.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagenesDelProyecto/Boton.png"))); // NOI18N
        botonProfAgreQuitRein.setText("Reinstituir");
        botonProfAgreQuitRein.setBorderPainted(false);
        botonProfAgreQuitRein.setContentAreaFilled(false);
        botonProfAgreQuitRein.setEnabled(false);
        botonProfAgreQuitRein.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        botonProfAgreQuitRein.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonProfAgreQuitReinActionPerformed(evt);
            }
        });

        botonProfAgreQuitGuardar.setBackground(new java.awt.Color(255, 255, 255));
        botonProfAgreQuitGuardar.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        botonProfAgreQuitGuardar.setForeground(new java.awt.Color(255, 255, 255));
        botonProfAgreQuitGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagenesDelProyecto/Boton.png"))); // NOI18N
        botonProfAgreQuitGuardar.setText("Guardar");
        botonProfAgreQuitGuardar.setBorderPainted(false);
        botonProfAgreQuitGuardar.setContentAreaFilled(false);
        botonProfAgreQuitGuardar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        botonProfAgreQuitGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonProfAgreQuitGuardarActionPerformed(evt);
            }
        });

        botonProfAgreQuitAnular.setBackground(new java.awt.Color(255, 255, 255));
        botonProfAgreQuitAnular.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        botonProfAgreQuitAnular.setForeground(new java.awt.Color(255, 255, 255));
        botonProfAgreQuitAnular.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagenesDelProyecto/Boton.png"))); // NOI18N
        botonProfAgreQuitAnular.setText("Anular");
        botonProfAgreQuitAnular.setBorderPainted(false);
        botonProfAgreQuitAnular.setContentAreaFilled(false);
        botonProfAgreQuitAnular.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        botonProfAgreQuitAnular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonProfAgreQuitAnularActionPerformed(evt);
            }
        });

        botonAtrasProfAgreQuit.setBackground(new java.awt.Color(255, 255, 255));
        botonAtrasProfAgreQuit.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        botonAtrasProfAgreQuit.setForeground(new java.awt.Color(255, 255, 255));
        botonAtrasProfAgreQuit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagenesDelProyecto/BotonRetroceso.png"))); // NOI18N
        botonAtrasProfAgreQuit.setText("Atrás");
        botonAtrasProfAgreQuit.setBorderPainted(false);
        botonAtrasProfAgreQuit.setContentAreaFilled(false);
        botonAtrasProfAgreQuit.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        botonAtrasProfAgreQuit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAtrasProfAgreQuitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelGradProfAgreQuitLayout = new javax.swing.GroupLayout(panelGradProfAgreQuit);
        panelGradProfAgreQuit.setLayout(panelGradProfAgreQuitLayout);
        panelGradProfAgreQuitLayout.setHorizontalGroup(
            panelGradProfAgreQuitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelGradProfAgreQuitLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(etiquetaProfAgreQuit)
                .addGap(186, 186, 186)
                .addComponent(botonAtrasProfAgreQuit)
                .addContainerGap())
            .addGroup(panelGradProfAgreQuitLayout.createSequentialGroup()
                .addGap(141, 141, 141)
                .addGroup(panelGradProfAgreQuitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(botonProfAgreQuitGuardar)
                    .addGroup(panelGradProfAgreQuitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(panelGradProfAgreQuitLayout.createSequentialGroup()
                            .addGap(30, 30, 30)
                            .addComponent(etiquetaProfAgreQuitDni)
                            .addGap(18, 18, 18)
                            .addComponent(textoProfAgreQuitDni, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(botonProfAgreQuitBuscar, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(separadorProfAgreQuit, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 611, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(panelGradProfAgreQuitLayout.createSequentialGroup()
                            .addGap(49, 49, 49)
                            .addGroup(panelGradProfAgreQuitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(panelGradProfAgreQuitLayout.createSequentialGroup()
                                    .addComponent(etiquetaProfAgreQuitNumTel)
                                    .addGap(18, 18, 18)
                                    .addComponent(textoProfAgreQuitNumTel, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(panelGradProfAgreQuitLayout.createSequentialGroup()
                                    .addComponent(etiquetaProfAgreQuitNomYApe)
                                    .addGap(18, 18, 18)
                                    .addComponent(textoProfAgreQuitNomYApe, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(panelGradProfAgreQuitLayout.createSequentialGroup()
                                    .addGroup(panelGradProfAgreQuitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(etiquetaProfAgreQuitEstado)
                                        .addComponent(etiquetaProfAgreQuitDom))
                                    .addGap(18, 18, 18)
                                    .addGroup(panelGradProfAgreQuitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(textoProfAgreQuitDom, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(etiquetaProfAgreQuitAcONoac, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(botonProfAgreQuitRein)))
                    .addComponent(botonProfAgreQuitAnular))
                .addContainerGap(207, Short.MAX_VALUE))
        );
        panelGradProfAgreQuitLayout.setVerticalGroup(
            panelGradProfAgreQuitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelGradProfAgreQuitLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelGradProfAgreQuitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(botonAtrasProfAgreQuit)
                    .addComponent(etiquetaProfAgreQuit))
                .addGap(30, 30, 30)
                .addGroup(panelGradProfAgreQuitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonProfAgreQuitBuscar)
                    .addComponent(textoProfAgreQuitDni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(etiquetaProfAgreQuitDni))
                .addGap(27, 27, 27)
                .addComponent(separadorProfAgreQuit, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addGroup(panelGradProfAgreQuitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textoProfAgreQuitNomYApe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(etiquetaProfAgreQuitNomYApe))
                .addGap(18, 18, 18)
                .addGroup(panelGradProfAgreQuitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textoProfAgreQuitNumTel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(etiquetaProfAgreQuitNumTel))
                .addGap(18, 18, 18)
                .addGroup(panelGradProfAgreQuitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelGradProfAgreQuitLayout.createSequentialGroup()
                        .addGroup(panelGradProfAgreQuitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(textoProfAgreQuitDom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(etiquetaProfAgreQuitDom))
                        .addGap(18, 18, 18)
                        .addGroup(panelGradProfAgreQuitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(etiquetaProfAgreQuitEstado)
                            .addComponent(etiquetaProfAgreQuitAcONoac, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(botonProfAgreQuitRein))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botonProfAgreQuitGuardar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botonProfAgreQuitAnular)
                .addContainerGap(53, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelGradProfAgreQuit, javax.swing.GroupLayout.DEFAULT_SIZE, 959, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelGradProfAgreQuit, javax.swing.GroupLayout.DEFAULT_SIZE, 545, Short.MAX_VALUE)
        );

        setBounds(0, 0, 975, 575);
    }// </editor-fold>//GEN-END:initComponents

    private void botonAtrasProfAgreQuitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAtrasProfAgreQuitActionPerformed
        dispose();
    }//GEN-LAST:event_botonAtrasProfAgreQuitActionPerformed

    private void botonProfAgreQuitBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonProfAgreQuitBuscarActionPerformed
        try{
            int Dni = Integer.parseInt(textoProfAgreQuitDni.getText());
            botonProfAgreQuitGuardar.setEnabled(false);
            Prestador pre = presData.buscarPrestador(Dni);
            if(pre.getTelefono()==0){
                limpiar();
            }else{
                textoProfAgreQuitNomYApe.setText(pre.getNombre());
                textoProfAgreQuitDom.setText(pre.getDomicilio());
                textoProfAgreQuitNumTel.setText(pre.getTelefono()+"");
                if(pre.isActivo()){
                    etiquetaProfAgreQuitAcONoac.setText("Activo");
                    botonProfAgreQuitRein.setEnabled(false);
                }else{
                    etiquetaProfAgreQuitAcONoac.setText("Inactivo");
                    botonProfAgreQuitRein.setEnabled(true);
                }
            }
        }catch(NumberFormatException ne){
            JOptionPane.showMessageDialog(null, "Ingrese un DNI válido para buscar a un Profesional");
            limpiar();
        }
    }//GEN-LAST:event_botonProfAgreQuitBuscarActionPerformed

    private void botonProfAgreQuitReinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonProfAgreQuitReinActionPerformed
        int Dni = Integer.parseInt(textoProfAgreQuitDni.getText());
        presData.reinstituirPrestador(Dni);
        limpiar();
    }//GEN-LAST:event_botonProfAgreQuitReinActionPerformed

    private void botonProfAgreQuitGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonProfAgreQuitGuardarActionPerformed
        try{
            if(textoProfAgreQuitDni.getText().isEmpty() || textoProfAgreQuitNumTel.getText().isEmpty()){
                JOptionPane.showMessageDialog(null, "Tiene que llenar la planilla para ingresar un Profesional");
            }else if(buscarDni(Integer.parseInt(textoProfAgreQuitDni.getText()))){
                JOptionPane.showMessageDialog(null, "El DNI ingresado ya le pertenece a un Profesional registrado");
            }else{
                int Dni = Integer.parseInt(textoProfAgreQuitDni.getText());
                int Tel = Integer.parseInt(textoProfAgreQuitNumTel.getText());
                Prestador prest = new Prestador();
                prest.setDni(Dni);
                prest.setNombre(textoProfAgreQuitNomYApe.getText());
                prest.setTelefono(Tel);
                prest.setDomicilio(textoProfAgreQuitDom.getText());
                prest.setActivo(true);
                presData.guardarPrestador(prest);
            }
        }catch(NumberFormatException ne){
            JOptionPane.showMessageDialog(null, "Error al ingresar, caracteres errónes");
        }catch(NullPointerException np){
            JOptionPane.showMessageDialog(null, "Tiene que llenar la planilla para ingresar un Profesional");
        }
        limpiar();
    }//GEN-LAST:event_botonProfAgreQuitGuardarActionPerformed

    private void botonProfAgreQuitAnularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonProfAgreQuitAnularActionPerformed
        try{
            int Dni = Integer.parseInt(textoProfAgreQuitDni.getText());
            presData.eliminarPrestador(Dni);
        }catch(NumberFormatException ne){
            JOptionPane.showMessageDialog(null, "Ingrese el DNI de un Profesional para anularlo");
        }catch(NullPointerException np){
            JOptionPane.showMessageDialog(null, "Tiene que ingresar el DNI de un Profesional para anularlo");
        }
        limpiar();
    }//GEN-LAST:event_botonProfAgreQuitAnularActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonAtrasProfAgreQuit;
    private javax.swing.JButton botonProfAgreQuitAnular;
    private javax.swing.JButton botonProfAgreQuitBuscar;
    private javax.swing.JButton botonProfAgreQuitGuardar;
    private javax.swing.JButton botonProfAgreQuitRein;
    private javax.swing.JLabel etiquetaProfAgreQuit;
    private javax.swing.JLabel etiquetaProfAgreQuitAcONoac;
    private javax.swing.JLabel etiquetaProfAgreQuitDni;
    private javax.swing.JLabel etiquetaProfAgreQuitDom;
    private javax.swing.JLabel etiquetaProfAgreQuitEstado;
    private javax.swing.JLabel etiquetaProfAgreQuitNomYApe;
    private javax.swing.JLabel etiquetaProfAgreQuitNumTel;
    private keeptoo.KGradientPanel panelGradProfAgreQuit;
    private javax.swing.JSeparator separadorProfAgreQuit;
    private javax.swing.JTextField textoProfAgreQuitDni;
    private javax.swing.JTextField textoProfAgreQuitDom;
    private javax.swing.JTextField textoProfAgreQuitNomYApe;
    private javax.swing.JTextField textoProfAgreQuitNumTel;
    // End of variables declaration//GEN-END:variables

    private void limpiar(){
        textoProfAgreQuitDni.setText("");
        textoProfAgreQuitDom.setText("");
        textoProfAgreQuitNomYApe.setText("");
        textoProfAgreQuitNumTel.setText("");
        etiquetaProfAgreQuitAcONoac.setText("");
        botonProfAgreQuitRein.setEnabled(false);
        botonProfAgreQuitGuardar.setEnabled(true);
    }
    
    private boolean buscarDni(int dni) {
        ArrayList<Prestador> prestador = presData.listarPrestador();
        boolean bd = false;
        for (Prestador pres : prestador) {
            if (pres.getDni() == dni) {
                bd = true;
                return bd;
            }
        }
        return bd;
    }
}